In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('D:/BE Lab Practicals/ML/ML Lab 4/diabetes.csv')
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   Pedigree  Age  Outcome  
0     0.627   50        1  
1     0.351   31        0  
2     0.672   32        1  
3     0.167   21        0  
4     2.288   33        1

In [3]:
data.isnull().sum()

Pregnancies      0
Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
Pedigree         0
Age              0
Outcome          0
dtype: int64

In [4]:
data.shape

(768, 9)

In [5]:
import numpy as np
import pandas as pd

# Replace 0 with NaN and fill NaN with column mean rounded
for column in data.columns[1:-3]:
    data[column] = data[column].replace(0, np.NaN)
    data[column] = data[column].fillna(round(data[column].mean(skipna=True)))

# Display first 10 rows to verify
print(data.head(10))

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0           72.0           35.0    156.0  33.6   
1            1     85.0           66.0           29.0    156.0  26.6   
2            8    183.0           64.0           29.0    156.0  23.3   
3            1     89.0           66.0           23.0     94.0  28.1   
4            0    137.0           40.0           35.0    168.0  43.1   
5            5    116.0           74.0           29.0    156.0  25.6   
6            3     78.0           50.0           32.0     88.0  31.0   
7           10    115.0           72.0           29.0    156.0  35.3   
8            2    197.0           70.0           45.0    543.0  30.5   
9            8    125.0           96.0           29.0    156.0  32.0   

   Pedigree  Age  Outcome  
0     0.627   50        1  
1     0.351   31        0  
2     0.672   32        1  
3     0.167   21        0  
4     2.288   33        1  
5     0.201   30        0  
6     0.248

In [6]:
X = data.iloc[:, :8] #Features
Y = data.iloc[:, 8:] #Predictor

In [7]:
#Perform Spliting
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [8]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score
from sklearn.datasets import load_iris

# Load a dataset for example
data = load_iris()
X = data.data
Y = data.target

# Split the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Initialize and fit the KNN classifier
knn = KNeighborsClassifier()
knn_fit = knn.fit(X_train, Y_train)
knn_pred = knn_fit.predict(X_test)

print("Confusion Matrix")
print(confusion_matrix(Y_test, knn_pred))
print("Accuracy Score:", accuracy_score(Y_test, knn_pred))
print("Recall Score:", recall_score(Y_test, knn_pred, average='weighted'))  # average='weighted' for multiclass
print("F1 Score:", f1_score(Y_test, knn_pred, average='weighted'))  # average='weighted' for multiclass
print("Precision Score:", precision_score(Y_test, knn_pred, average='weighted'))  # average='weighted' for multiclass

Confusion Matrix
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy Score: 1.0
Recall Score: 1.0
F1 Score: 1.0
Precision Score: 1.0


In [9]:
from sklearn.model_selection import cross_val_score 
import numpy as np
#create a new KNN model
knn_cv = KNeighborsClassifier(n_neighbors=3)
#train model with cv of 5
cv_scores = cross_val_score(knn_cv, X, Y, cv=5)
#print each cv score (accuracy) and average them print(cv_scores)
print(cv_scores)
print('cv_scores mean:{}'.format(np.mean(cv_scores)))

[0.96666667 0.96666667 0.93333333 0.96666667 1.        ]
cv_scores mean:0.9666666666666668


In [10]:
from sklearn.model_selection import GridSearchCV
#create new a knn model
knn2 = KNeighborsClassifier()
#create a dictionary of all values we want to test for n_neighbors 
param_grid = {'n_neighbors': np.arange(1, 25)}
#use gridsearch to test all values for n_neighbors 
knn_gscv = GridSearchCV(knn2, param_grid, cv=5)
#fit model to data
knn_gscv.fit(X, Y)
knn_gscv.best_params_

{'n_neighbors': 6}

In [11]:
knn_gscv.best_score_

0.9800000000000001